language: scala
sudo: false
jdk: oraclejdk8
env:
  matrix:
  - G8_VERSION="0.10.0"
  - G8_VERSION="0.11.0-M1"
  - G8_VERSION="0.11.0-M2"
script:
- wget http://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt-launch/1.1.0/sbt-launch.jar
- java -Xmx2G -jar sbt-launch.jar @${G8_VERSION}-launchconfig unfiltered/unfiltered.g8
